    <nav class="bg-black">
      <div
        class="flex items-center justify-between max-w-screen-xl mx-auto p-4"
      >
        <button
          data-collapse-toggle="mega-menu"
          type="button"
          class="burger inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden z-10"
          aria-controls="mega-menu"
          aria-expanded="false"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="27"
            height="28"
            viewBox="0 0 27 28"
            fill="none"
          >
            <path
              d="M2.95312 6.83887H24.4688M2.95312 14.0107H21.0938M2.95312 21.1826H24.4688"
              stroke="white"
              stroke-width="2.10938"
            />
          </svg>
        </button>
        <a
          href="https://g2esports.com"
          class="flex items-center space-x-3 rtl:space-x-reverse"
        >
          <img
            src="./assets/G2-Esports-Logo.webp"
            class="h-12"
            alt="G2 Esports Logo"
          />
        </a>
        <div
          class="flex items-center md:order-2 space-x-1 md:space-x-2 rtl:space-x-reverse"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="28"
            height="28"
            viewBox="0 0 28 28"
            fill="none"
          >
            <path
              d="M23.4316 23.292L18.3438 18.2295M20.546 12.5679C20.546 14.1182 20.0863 15.6337 19.225 16.9227C18.3637 18.2118 17.1395 19.2164 15.7072 19.8097C14.2749 20.403 12.6989 20.5582 11.1784 20.2558C9.65787 19.9533 8.26119 19.2068 7.16497 18.1105C6.06874 17.0143 5.32221 15.6176 5.01976 14.0971C4.71731 12.5766 4.87254 11.0006 5.46581 9.56829C6.05908 8.136 7.06375 6.91181 8.35278 6.05051C9.6418 5.18921 11.1573 4.72949 12.7076 4.72949C13.7369 4.72949 14.7562 4.93224 15.7072 5.32616C16.6582 5.72008 17.5223 6.29745 18.2502 7.02532C18.9781 7.75318 19.5554 8.61729 19.9494 9.56829C20.3433 10.5193 20.546 11.5386 20.546 12.5679Z"
              stroke="white"
              stroke-width="2.10938"
            />
          </svg>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="28"
            height="28"
            viewBox="0 0 28 28"
            fill="none"
          >
            <path
              d="M9.78711 8.10449C9.78711 5.10707 11.6223 4.30762 13.9004 4.30762C16.1785 4.30762 18.0137 5.10707 18.0137 8.10449"
              stroke="white"
              stroke-width="2.10938"
            />
            <path
              d="M7.0095 19.0073L7.69007 9.00098H21.1575L21.8381 19.0073C21.8764 19.5696 21.7987 20.1338 21.6099 20.6648C21.4211 21.1959 21.1252 21.6825 20.7405 22.0945C20.3559 22.5065 19.8907 22.835 19.3738 23.0597C18.857 23.2845 18.2994 23.4006 17.7358 23.401H11.1135C10.5497 23.4009 9.992 23.2849 9.47492 23.0603C8.95784 22.8356 8.49244 22.5071 8.10761 22.0951C7.72278 21.6831 7.42673 21.1964 7.23783 20.6652C7.04893 20.1341 6.97121 19.5697 7.0095 19.0073Z"
              stroke="#A7A2A2"
              stroke-width="2.4"
            />
          </svg>
          <img src="./assets/flag-eu_50x50.png" alt="EU logo" />
        </div>
        <div
          class="items-center w-80 justify-between h-screen md:flex md:h-auto md:order-1 hidden"
        >
          <ul
            class="flex flex-col mt-4 font-medium md:flex-row md:mt-0 md:space-x-8 rtl:space-x-reverse"
          >
            <li>
              <a
                href="#"
                class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0"
                >Jersey</a
              >
            </li>
            <li>
              <a
                href="#"
                class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0"
                >Collabs</a
              >
            </li>
            <li>
              <a
                href="#"
                class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0"
                >Sleeve</a
              >
            </li>
            <li>
              <a
                href="#"
                class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0"
                >Jacket</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div
      id="mega-menu"
      class="flex absolute top-0 left-0 bg-black items-start pt-24 pl-6 w-80 h-screen md:flex md:h-auto md:order-1 -translate-x-full md:top-auto md:left-auto"
    >
      <ul
        class="flex flex-col mt-4 font-medium md:flex-row md:mt-0 md:space-x-8 rtl:space-x-reverse"
      >
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-white hover:text-red-600 md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0"
            >Jersey</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0 hover:text-red-600"
            >Collabs</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0 hover:text-red-600"
            >Sleeve</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0 hover:text-red-600"
            >Jacket</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-white md:hover:bg-transparent md:border-0 md:hover:text-red-600 md:p-0 hover:text-red-600"
            >G2 App</a
          >
        </li>
      </ul>
    </div>
    <script>
      document.querySelector(".burger").addEventListener("click", function () {
        megaMenu = document.getElementById("mega-menu");
        megaMenu.classList.toggle("right-full");
        megaMenu.classList.toggle("translate-x-0");
      });
    </script>