
  <section class="newestitems">
  <div class="flex flex-col items-center py-2 px-4 text-center">
    <h3 class="font-bold uppercase">G2 Esports</h3>
    <h2 class="text-red-600 text-4xl font-bold uppercase">Newest items</h2>
    <p class="font-medium mt-2">Do not miss out on the freshest esports merch. Hurry, these items sell out in a matter of seconds!</p>
    <button class="px-3 py-2 border border-red-600 uppercase text-red-600 font-semibold mt-4 hover:bg-red-600 hover:text-white">View all</button>
  </div>
  <div>
    <div>
   <!-- Insérer les items ici  -->
  </div>
</section>
